{{- range .Values.serviceAccounts }}
{{- $accountName := .name -}}
{{- $accountNs:= .namespace -}}

{{- range .bindings }}
{{ if eq .scope "cluster" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: {{ $.Values.tenant }}
  name: "svc-{{ $accountName }}-{{ .role }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .role }}
subjects:
- kind: ServiceAccount
  name: {{ $accountName }}
  namespace: {{ $accountNs }}
{{- end }}

{{ if eq .scope "namespace" }}
{{- range $namespace := .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: {{ $.Values.tenant }}
  name: "svc-{{ $accountName }}-{{ .role }}"
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .role }}
subjects:
- kind: ServiceAccount
  name: {{ $accountName }}
  namespace: {{ $accountNs }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- range .Values.groups }}
{{- $accountName := .name -}}
{{- $accountId := .id -}}

{{- range .bindings }}
{{- $role := .role -}}

{{ if eq .scope "cluster" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: {{ $.Values.tenant }}
  name: "aad-{{ $accountName }}-{{ $role }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $accountId }}
{{- end }}

{{ if eq .scope "namespace" }}
{{- range $namespace := .namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: {{ $.Values.tenant }}
  name: "aad-{{ $accountName }}-{{ $role }}"
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $accountId }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
