{{- range .Values.serviceAccounts }}
{{ if ne .name "default" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: {{ $.Values.tenant }}
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
